export const events = {
  READY: "READY",
  NOT_READY: "NOT_READY",
  YOU_ARE_READY: "YOU_ARE_READY",
  YOU_ARE_NOT_READY: "YOU_ARE_NOT_READY",
  ANOTHER_PLAYER_READY: "ANOTHER_PLAYER_READY",
  ANOTHER_PLAYER_NOT_READY: "ANOTHER_PLAYER_NOT_READY"
}
